---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "4 20 * * 0"

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: docker-compose up -d
        run: >
          docker-compose up -d

      - name: Inspect Docker container.
        run: >
          sleep 3 && docker ps

      - name: Test that we're getting the expected result.
        run: curl http://localhost:9924/metrics | grep "Could not resolve host"